export default [
    {
      "theme": "light",
      "color-scheme": "light",
      "primary": "#570df8",
      "primary-content": "#ffffff",
      "secondary": "#f000b8",
      "secondary-content": "#ffffff",
      "accent": "#37cdbe",
      "accent-content": "#163835",
      "neutral": "#3d4451",
      "neutral-content": "#ffffff",
      "base-100": "#ffffff",
      "base-content": "#1f2937",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "--rounded-box": "1rem",
      "--rounded-btn": "0.5rem"
    },
    {
      "theme": "dark",
      "color-scheme": "dark",
      "primary": "#6419e6",
      "primary-content": "#ffffff",
      "secondary": "#d926a9",
      "secondary-content": "#ffffff",
      "accent": "#1fb2a6",
      "accent-content": "#ffffff",
      "neutral": "#2a2e37",
      "neutral-content": "#a6adbb",
      "base-100": "#1d232a",
      "base-content": "#a6adbb",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "--rounded-box": "1rem",
      "--rounded-btn": "0.5rem"
    },
    {
      "theme": "aqua",
      "color-scheme": "dark",
      "primary": "#09ecf3",
      "primary-content": "#005355",
      "secondary": "#966fb3",
      "secondary-content": "#ffffff",
      "accent": "#ffe999",
      "accent-content": "#000000",
      "neutral": "#3b8ac4",
      "neutral-content": "#ffffff",
      "base-100": "#345da7",
      "base-content": "#ffffff",
      "info": "#2563eb",
      "success": "#16a34a",
      "warning": "#d97706",
      "error": "oklch(73.95% 0.19 27.33)",
      "--rounded-box": "1rem",
      "--rounded-btn": "0.5rem"
    },
    {
      "theme": "cupcake",
      "color-scheme": "light",
      "primary": "#65c3c8",
      "primary-content": "#ffffff",
      "secondary": "#ef9fbc",
      "secondary-content": "#ffffff",
      "accent": "#eeaf3a",
      "accent-content": "#ffffff",
      "neutral": "#291334",
      "neutral-content": "#ffffff",
      "base-100": "#faf7f5",
      "base-content": "#291334",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "--rounded-box": "1rem",
      "--rounded-btn": "1.9rem"
    },
    {
      "theme": "bumblebee",
      "color-scheme": "light",
      "primary": "#e0a82e",
      "primary-content": "#181830",
      "secondary": "#f9d72f",
      "secondary-content": "#181830",
      "accent": "#181830",
      "accent-content": "#f9d72f",
      "neutral": "#181830",
      "neutral-content": "#ffffff",
      "base-100": "#ffffff",
      "base-content": "#181830",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "--rounded-box": "0.5rem",
      "--rounded-btn": "0.5rem"
    },
    {
      "theme": "cyberpunk",
      "color-scheme": "light",
      "primary": "#ff7598",
      "primary-content": "#ffffff",
      "secondary": "#75d1f0",
      "secondary-content": "#ffffff",
      "accent": "#c07eec",
      "accent-content": "#ffffff",
      "neutral": "#423f00",
      "neutral-content": "#fff000",
      "base-100": "#fff000",
      "base-content": "#423f00",
      "info": "#2563eb",
      "success": "#16a34a",
      "warning": "#d97706",
      "error": "#dc2626",
      "--rounded-box": "0",
      "--rounded-btn": "0"
    },
    {
      "theme": "valentine",
      "color-scheme": "light",
      "primary": "#e96d7b",
      "primary-content": "#ffffff",
      "secondary": "#a991f7",
      "secondary-content": "#ffffff",
      "accent": "#66b1b3",
      "accent-content": "#ffffff",
      "neutral": "#af4670",
      "neutral-content": "#f0d6e8",
      "base-100": "#f0d6e8",
      "base-content": "#632c3b",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "--rounded-box": "1rem",
      "--rounded-btn": "1.9rem"
    },
    {
      "theme": "forest",
      "color-scheme": "dark",
      "primary": "#1eb854",
      "primary-content": "#ffffff",
      "secondary": "#1db88e",
      "secondary-content": "#ffffff",
      "accent": "#1db8ab",
      "accent-content": "#ffffff",
      "neutral": "#19362d",
      "neutral-content": "#a6adbb",
      "base-100": "#171212",
      "base-content": "#a6adbb",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272",
      "--rounded-box": "0.2rem",
      "--rounded-btn": "0.2rem"
    }
  ];